config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'tv_shows/show'
  get 'tv_shows/search_results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tv_shows_controller.rb
require 'httparty'

class TvShowsController < ApplicationController
  def show
    tv_id = params[:id]
    options = {}
    options[:api_key] = "fb6a1d3f38c3d97f67df6d141f936f29"
    options[:language] = "en-US"


    @tv_show = HTTParty.get(
      "https://api.themoviedb.org/3/tv/#{tv_id}",
      {
        headers: {
          'Content-Type' => 'application/x-www-form-urlencoded'
        },
        query: options
      }
    )
  end

  def search_results
    tv_show_name = params[:search]

    if params[:search].empty?
      redirect_to welcome_index_path
    end

    # if params[:search]["results"] == 0
    #   return print "No Results"
    # end
    options = {}
    options[:api_key] = "fb6a1d3f38c3d97f67df6d141f936f29"
    options[:language] = "en-US"
    options[:query] = tv_show_name
    options[:page] = 1
    @tv_show = HTTParty.get(
      "https://api.themoviedb.org/3/search/tv",
      {
        headers: {
          'Content-Type' => 'application/x-www-form-urlencoded'
        },
        query: options
      }
    )

  end


end

app/controllers/welcome_controller.rb
require 'httparty'

class WelcomeController < ApplicationController

  def index
    #TMDb.api_key = 'fb6a1d3f38c3d97f67df6d141f936f29'

    #Tmdb::Api.key("fb6a1d3f38c3d97f67df6d141f936f29")
    #Tmdb::Api.key("en")
    #@tv_shows = Tmdb::TV.popular

    @tv_shows = HTTParty.get("https://api.themoviedb.org/3/tv/popular?api_key=fb6a1d3f38c3d97f67df6d141f936f29&language=en-US")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvDiscovery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  </head>

  <body>



    <nav class="navbar navbar-inverse">
      <div class="container-fluid">

        <ul class="nav navbar-nav">
        </ul>
      </div>
      <div class="topnav">
        <a class="active" href="<%= welcome_index_path %>"<a>Home</a>
        <div class="search-container">
          <%= form_tag(tv_shows_search_results_path, method: :get) do  %>
            <%= text_field_tag(:search, params[:search], placeholder: 'TV show search...')%>
            <%= submit_tag ("Search") %>
            <button type="submit"><i class="fa fa-search"></i></button>
          <%  end  %>
        </div>
      </div>
      <%= yield %>


    <style>
      h1 {
        color: light pink;
        font-family: verdana;
        font-size: 300%;
      }
      p  {
        color: green;
        font-family: courier;
        font-size: 160%;
      }
      body {background-color: pink;}
      /* tr:hover {background-color:#f5f5f5;} */

    </style>

  </body>
</html>

app/views/tv_shows/search_results.html.erb
</br></br></br>

<body>

  <div class="table">
    <table class="table table-striped">

      <thead>
        <tr style="background: #A24EBC">
          <th scope="col">Name</th>
          <th scope="col">Overview</th>
        </tr>
      </thead>

      <tbody>
        <% for i in @tv_show["results"]%>
        <tr>
          <td><%= link_to i["name"], tv_shows_show_path(:id => i["id"]) %></td>
          <td align="left"><%= i["overview"]%></td>

        </tr>
        <% end%>
      </tbody>

    </table>
  </div>

</body>

app/views/tv_shows/show.html.erb
</br></br></br>

<body>

  <div class="table">
    <table class="table table-striped">

      <thead>
        <tr style="background: #A24EBC">
          <th scope="col 6">Poster</th>
          <th scope="col 6">Name</th>
          <th scope="col 6">Overview</th>
          <th scope="col 6">First Air Date</th>
          <th scope="col 6">Last Air Date</th>
          <th scope="col 6">Genre</th>
          <th scope="col 6">Number of Seasons</th>
          <th scope="col 6">Number of Episodes</th>

        </tr>
      </thead>

      <tbody>
        <tr>
          <td><a class="active"> <%= image_tag ("https://image.tmdb.org/t/p/w370_and_h556_bestv2/" + @tv_show["poster_path"]), :style => "border: 1px solid black", :size => "200" %></a></td>
          <td><%= @tv_show["name"] %></td>
          <td align="left"><%= @tv_show["overview"]%></td>
          <td><%= @tv_show["first_air_date"]%></td>
          <td><%= @tv_show["last_air_date"]%></td>
          <td>
            <% for genre in @tv_show["genres"] %>
              <%= genre["name"]%>
              <br>
            <% end %>
          </td>
          <td><%= @tv_show["number_of_seasons"]%></td>
          <td><%= @tv_show["number_of_episodes"]%></td>

        </tr>
      </tbody>

    </table>
  </div>

</body>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">
  <head>



  </head>
  <body>

    <title>The TV Database</title>

    <h1>The TV Database</h1>


    <br />
    <br />


    <div class="table-responsive">
      <table class="table table-striped table-hover">

          <thead>
          <tr style="background: #A24EBC">
            <th>Poster</th>
            <th>Name</th>
            <th>Ranking</th>
          </tr>
        </thead>
        <tbody>
          <% for i in @tv_shows["results"] do %>
          <tr>
            <td>
                <% if !i["poster_path"].nil? %>
                   <a class="active"> <%= image_tag ("https://image.tmdb.org/t/p/w370_and_h556_bestv2/" + i["poster_path"]), :style => "border: 1px solid black", :size => "200" %></a>

                  </td>
                  <td><%= link_to i["name"], tv_shows_show_path(:id => i["id"]) %></td>
                  <td><%= i["popularity"] %></td>
                <% end %>
          </tr>
          <% end %>
        </tbody>

    </table>
  </div>


  </body>
</html>